<?php

namespace Piledge\CommentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function findAllByAuthorAndDocument($doc_id) {

        $qb = $this->createQueryBuilder('c')
                   ->join('c.author', 'a')
                   ->join('c.document', 'd')
                   ->addSelect('a')
                   ->addSelect('d')
                   ->Where('d.document_id = :doc_id')
                   ->setParameter('doc_id', $doc_id)
                   ->orderBy('c.comment_created_at', 'DESC');

        return $qb->getQuery()->getArrayResult();

    }

    public function countByDocument($doc_id) {

        $qb = $this->createQueryBuilder('c')
                   ->join('c.document', 'd')
                   ->addSelect('d')
                   ->Where('d.document_id = :doc_id')
                   ->setParameter('doc_id', $doc_id);

        return $qb->getQuery()->getSingleResult();

    }



}
