login:
    pattern:  /signin
    defaults: { _controller: PiledgeAuthorBundle:Author:login }

login_check:
    pattern:  /login_check

logout:
    pattern:  /signout

piledgeAuthor_signup:
    pattern:  /Signup
    defaults: { _controller: PiledgeAuthorBundle:Author:signup }
