parameters:
#    piledge_comment.example.class: Piledge\CommentBundle\Example

services:
#    piledge_comment.example:
#        class: %piledge_comment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
