<?php

namespace Piledge\MessageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{

    public function findMsg_unread($reid) {
        
        $qb = $this->createQueryBuilder('m')
                   ->where('m.message_receiver_id = :reid')
                   ->setParameter(':reid', $reid)
                   ->andWhere('m.message_is_read = false');

         return count($qb->getQuery()->getResult());
         
    }


    public function findInbox($reid) {
         $qb = $this->createQueryBuilder('m')
                    ->join('m.author', 'a')
                    ->addSelect('a')
                    ->where('m.message_receiver_id = :reid')
                    ->setParameter(':reid', $reid);

         return $qb->getQuery()->getArrayResult();

    }
}
