piledge_comment:
    resource: "@PiledgeCommentBundle/Resources/config/routing.yml"
    prefix:   /

piledge_author:
    resource: "@PiledgeAuthorBundle/Resources/config/routing.yml"
    prefix:   /

piledge_document:
    resource: "@PiledgeDocumentBundle/Resources/config/routing.yml"
    prefix:   /

piledge_gle:
    resource: "@PiledgeGleBundle/Resources/config/routing.yml"
    prefix:   /
