security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Piledge\AuthorBundle\Entity\Author: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_AUTHOR, ROLE_MODO]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        from_bb:
            entity: { class: Piledge\AuthorBundle\Entity\Author, property: author_username}

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        guard:
            pattern: ^/
            anonymous: true
            provider:  from_bb
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: /


    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
