parameters:
#    piledge_document.example.class: Piledge\DocumentBundle\Example

services:
#    piledge_document.example:
#        class: %piledge_document.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    piledge_document.twig_extension:
        class: Piledge\DocumentBundle\Twig\AppExtension
        public: false
        tags: 
            - { name: twig.extension }
