parameters:
#    piledge_message.example.class: Piledge\MessageBundle\Example

services:
#    piledge_message.example:
#        class: %piledge_message.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
