parameters:
#    piledge_gle.example.class: Piledge\GleBundle\Example

services:
#    piledge_gle.example:
#        class: %piledge_gle.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
