<?php

namespace Piledge\AuthorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends EntityRepository
{
    public function findOneByUsername($username) {
        $qb = $this->createQueryBuilder('a');
        $qb->where('a.author_username = :username')
            ->setParameter('username', $username);

        return $qb->getQuery()->getOneOrNullResult();
        //return $qb->getQuery()->getSingleResult();
    }
}
