<?php

namespace Piledge\DocumentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository {

    public function findByDateDesc() {

        $qb = $this->createQueryBuilder('d');
        $qb->orderBy('d.document_created_at', 'DESC');

        return $qb->getQuery()->getArrayResult();
    }
}
